let products = [
  {
    name: "product one",
    id: 1,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/s1.jpg",
    quantity: 1,
    size: "small",
    isMe: false,
  },
  {
    name: "product two",
    id: 2,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/s2.jpg",
    quantity: 1,
    size: "large",
    isMe: false,
  },
  {
    name: "product three",
    id: 3,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/s3.jpg",
    quantity: 1,
    size: "medium",
    isMe: false,
  },
  {
    name: "product four",
    id: 4,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/s4.jpg",
    quantity: 1,
    size: "small",
    isMe: false,
  },
  {
    name: "product five",
    id: 5,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/shirt.jpg",
    quantity: 1,
    size: "small",
    isMe: false,
  },
  {
    name: "product six",
    id: 6,
    title: "Lorem ipsum dolor, sit amet adipisicing",
    img: "/assets/shirt2.jpg",
    quantity: 1,
    size: "large",
    isMe: false,
  },
];
